// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGE7DIkxaRYcDVhQ1TQpi0MEnRVlUyY6k',
    appId: '1:821757181698:web:66da1558bb0c62716c0c1b',
    messagingSenderId: '821757181698',
    projectId: 'residence-log',
    authDomain: 'residence-log.firebaseapp.com',
    databaseURL: 'https://residence-log-default-rtdb.firebaseio.com',
    storageBucket: 'residence-log.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC--OkHK9IpDJqD6G6pzPsRLA1dBgwd70k',
    appId: '1:821757181698:android:77af46954d1097706c0c1b',
    messagingSenderId: '821757181698',
    projectId: 'residence-log',
    databaseURL: 'https://residence-log-default-rtdb.firebaseio.com',
    storageBucket: 'residence-log.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcXZkOcckYBHVUT0LZFxLGUVydKsrgss',
    appId: '1:821757181698:ios:dbaa908230d0795b6c0c1b',
    messagingSenderId: '821757181698',
    projectId: 'residence-log',
    databaseURL: 'https://residence-log-default-rtdb.firebaseio.com',
    storageBucket: 'residence-log.appspot.com',
    iosClientId: '821757181698-fi94hbanaelbpj5go7qen6dc6rfcdr58.apps.googleusercontent.com',
    iosBundleId: 'com.example.residenceLog',
  );
}
